version:  "3.7"
services:
  jupyter:
      image: jupyter/datascience-notebook:latest
      volumes:
        - ./jupyter/notebooks:/home/jovyan/work
      ports:
        - 8888:8888

  postgres:
    image: postgres:latest
    restart: 'always'
    #env_file:
    #  - ./config/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:

volumes:
  postgres_data:

