[admin]
user="admin"
password="admin"
email="test@gmail.com"
database= "test"
domain="platform.test"
docker_user = "projectgades"
docker_password = "ShadoWsong000"

[services]
proxy = "traefik"

[cluster]
name="mlstack"
manager=["china.medien.uni-weimar.de"]
worker=["zerg.medien.uni-weimar.de", "peru.medien.uni-weimar.de"]
manager_ip=["141.54.159.91"]
worker_ip=["141.54.159.140", "141.54.159.97"]
user= "marcel"
password= "marcel!"