[admin]
user="admin"
password="admin"
database= "test"
domain="localhost"

[monitoring]

[cluster]
manager=["china.medien.uni-weimar.de"]
worker=["peru.medien.uni-weimar.de"]
user= "marcel"
password= "marcel!"