[admin]
user="admin"
password="admin"
email="test@gmail.com"
database= "test"
domain="platform.test"
docker_user = "projectgades"
docker_password = "ShadoWsong000"

[monitoring]

[services]
proxy="traefik"


[cluster]
name="mlstack"
manager=["141.54.139.79"]
worker=["peru.medien.uni-weimar.de"]
manager_ip=["141.54.139.79"]
worker_ip=["141.54.159.97"]
user= "marcel"
password= "marcel!"

[cluster]
name="mlstack"
manager=["china.medien.uni-weimar.de"]
worker=["peru.medien.uni-weimar.de", "tibet.medien.uni-weimar.de"]
manager_ip=["141.54.159.91"]
worker_ip=["141.54.159.97","141.54.159.95"]
user= "marcel"
password= "marcel!"