[admin]
user="admin"
password="admin"
email="test@gmail.com"
database= "test"
domain="platform.test"
docker_user = "projectgades"
docker_password = "ShadoWsong000"


[services]
proxy="traefik"

[cluster]
name="mlstack"
manager=["tibet.medien.uni-weimar.de"]
worker=["141.54.139.89"]
manager_ip=["141.54.159.95"]
worker_ip=["141.54.139.89"]
user= "marcel"
password= "marcel!"