---
- name: Install Packages
  apt:
    name: ["ntp", "python", "tcpdump", "wget", "openssl", "curl", "python-pip", "python3", "python3-pip"]
    state: latest
    update_cache: yes
  ignore_errors: true
- name: Deinstall Docker Python Packages
  pip:
    name: ["docker", "docker-py", "requests"]
    state: absent
  ignore_errors: true
- name: Install Python Packages
  pip:
    name: ["docker", "requests"]
    state: latest
  ignore_errors: true