---
- name: Install Packages
  apt:
    name: ["ntp", "python", "tcpdump", "wget", "openssl", "curl", "python-pip", "python3", "python3-pip"]
    state: latest
    update_cache: yes

- name: Deinstall Docker Python Packages
  pip:
    name: "docker"
    state: absent

- name: Install Python Packages
  pip:
    name: ["docker-py", "requests"]
    state: latest