traefik:
  image: traefik
  command: --web \
    --docker \
    --docker.swarmmode \
    --docker.domain=${DOMAIN} \
    --docker.watch \
    --logLevel=DEBUG\
    --web.metrics.prometheus \
    --web.address=:8088
  networks:
    - traefik-net
  ports:
      - target: 80
        published: 80
        mode: host
      - target: 8088
        published: 8088
        mode: host
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
  depends_on:
    - consul-leader
