traefik:
  image: traefik
  command: --web \
    --docker \
    --docker.swarmmode \
    --docker.domain=${DOMAIN} \
    --docker.watch \
    --logLevel=DEBUG
  networks:
    - traefik-net
  ports:
    - "8080:8080"
    - "80:80"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
  depends_on:
    - consul-leader
