---
- name: install docker
  become: true
  hosts: nodes
  roles:
    - docker-installation

- name: install modules
  become: true
  hosts: nodes
  roles:
    - install-modules

- name: Generate Ceritificate
  become: true
  hosts: manager
  roles:
    - generate-certificate

- name: Initialize Registry
  become: true
  hosts: nodes
  roles:
    - init-registry