prometheus:
  image: stefanprodan/swarmprom-prometheus:v2.5.0
  volumes:
    - ./prometheus/:/etc/prometheus/
    - prometheus_data:/prometheus
  command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=24h'
  ports:
    - 9090:9090
  links:
    - cadvisor:cadvisor
  depends_on:
    - cadvisor
  restart: always